### ISSUE TITLE
Wow! App Topic page is blank!!!!

### ISSUE THREAD

**Issue by dealson4ne** [iilab/openmentoring-mobile#68]
I just opened my Openmentoring App and I was greeted with a blank topic page. 
even after attempts to refresh my the page, there was no content displayed apart from the search bar and the window Title (Topic).

I have also rebooted my phone. However after trying the App again, I still get the same results. 

My phone app details are: 
Manufacturer; ZOPO
Model: ZP999
Platform: Android
Platform Version: 4.4.2
App Version: 0.0.4

**Comment by bsenyk** [comment]
@dealson4ne Thanks for reporting this. Does the list reappear if you pull down to refresh it?

**Comment by dealson4ne** [comment]
No it does not appear at all even after restarting the phone.

**Comment by bsenyk** [comment]
@dealson4ne Ok, I have a few more things for you to try:
1. Make sure you have internet access by attempting to use the android browser to go to a website (it should work without internet access, but this will help us figure out the source of the issue).
2. Try to fully exit the app without restarting the phone by using method 1 or 2 on [this page](http://www.wikihow.com/Close-Apps-on-Android). Then open it again to see if that makes a difference.
3. Using F-Droid, uninstall and then reinstall the OpenMentoring app.  Unfortunately this will means you'll need to re-download topics.

Let me know what works so that I can pinpoint the issue.

Thanks!

**Comment by bsenyk** [comment]
I'm not sure if this is still happening, but I believe a fix will be in the 0.2.0 release
